

GET http://localhost:3000/api/productos HTTP/1.1
content-type: application/json
###
POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{
    "nombre": "camisa",
    "precio": 1200,
    "descripcion": "email@mail.com",
    "active": true,
    "imagen": "aca iria la url de la imagen",
    "id_categoria": 1
}
###
PUT http://localhost:3000/api/productos/1 HTTP/1.1
content-type: application/json

{
    "nombre": "Camiseta",
    "precio": 1500,
    "descripcion": "Remera de talle S oversize",
    "active": true,
    "imagen": "aca iria la url de la imagen",
    "id_categoria": 1
}

###
DELETE http://localhost:3000/api/productos/4 HTTP/1.1
content-type: application/json