

GET http://localhost:3000/api/productos HTTP/1.1
content-type: application/json
###
POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{
    "nombre": "Neumatico de Rally",
    "precio": 42000,
    "descripcion": "Para rally dakar",
    "active": 1,
    "imagen": "/front/assets/images/neumaticos.jpg",
    "id_categoria": 1
}
###
PUT http://localhost:3000/api/productos/1 HTTP/1.1
content-type: application/json

    {
     "nombre": "Bateria de 10.000 mAh",
      "precio": 10500,
      "descripcion": "Bateria",
      "active": true,
      "imagen": "aca iria la url de la imagen",
      "id_categoria": 3
    }

###
DELETE http://localhost:3000/api/productos/4 HTTP/1.1
content-type: application/json